# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppChallenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppChallenge

  target 'AppChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AppChallengeUITests' do
    # Pods for testing
  end

end
