platform :ios, '12.0'

use_frameworks!
inhibit_all_warnings!

def pods
  # Pods for shareinvestor
  pod 'Alamofire'
  pod 'KeychainAccess'
  pod 'Moya'
  pod 'R.swift', '~> 5.1.0'
  pod 'SnapKit'
  pod 'SVProgressHUD'
  pod 'Swinject', '~> 2.6.0'
  pod 'SwinjectStoryboard'
end

target 'AppChallenge' do
  pods
end

target 'AppChallengeTests' do
  pods
end

target 'AppChallengeUITests' do
  pods
end
